FROM node:20-alpine3.18 as builder

WORKDIR /app

COPY isee-server/ ./

RUN npm install
RUN npm run build && rm -rf node_modules && npm install --production

FROM node:20-alpine3.18 as runner

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.prod.env ./.dev.env

EXPOSE $PORT
CMD ["npm", "run", "start:prod"]